from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget)
import Recursos_qrc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(900, 700)
        MainWindow.setMinimumSize(QSize(700, 505))
        MainWindow.setMaximumSize(QSize(900, 700))
        palette = QPalette()
        gradient = QLinearGradient(0, 0, 1, 0)
        gradient.setSpread(QGradient.PadSpread)
        gradient.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient.setColorAt(0, QColor(211, 211, 211, 255))
        gradient.setColorAt(0.0454545, QColor(211, 211, 211, 255))
        gradient.setColorAt(1, QColor(211, 211, 211, 255))
        brush = QBrush(gradient)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        gradient1 = QLinearGradient(0, 0, 1, 0)
        gradient1.setSpread(QGradient.PadSpread)
        gradient1.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient1.setColorAt(0, QColor(211, 211, 211, 255))
        gradient1.setColorAt(0.0454545, QColor(211, 211, 211, 255))
        gradient1.setColorAt(1, QColor(211, 211, 211, 255))
        brush1 = QBrush(gradient1)
        palette.setBrush(QPalette.Active, QPalette.Text, brush1)
        gradient2 = QLinearGradient(0, 0, 1, 0)
        gradient2.setSpread(QGradient.PadSpread)
        gradient2.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient2.setColorAt(0, QColor(211, 211, 211, 255))
        gradient2.setColorAt(0.0454545, QColor(211, 211, 211, 255))
        gradient2.setColorAt(1, QColor(211, 211, 211, 255))
        brush2 = QBrush(gradient2)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        brush3 = QBrush(QColor(255, 255, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(104, 129, 50, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        gradient3 = QLinearGradient(0, 0, 1, 0)
        gradient3.setSpread(QGradient.PadSpread)
        gradient3.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient3.setColorAt(0, QColor(211, 211, 211, 255))
        gradient3.setColorAt(0.0454545, QColor(211, 211, 211, 255))
        gradient3.setColorAt(1, QColor(211, 211, 211, 255))
        brush5 = QBrush(gradient3)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        gradient4 = QLinearGradient(0, 0, 1, 0)
        gradient4.setSpread(QGradient.PadSpread)
        gradient4.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient4.setColorAt(0, QColor(211, 211, 211, 255))
        gradient4.setColorAt(0.0454545, QColor(211, 211, 211, 255))
        gradient4.setColorAt(1, QColor(211, 211, 211, 255))
        brush6 = QBrush(gradient4)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        gradient5 = QLinearGradient(0, 0, 1, 0)
        gradient5.setSpread(QGradient.PadSpread)
        gradient5.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient5.setColorAt(0, QColor(211, 211, 211, 255))
        gradient5.setColorAt(0.0454545, QColor(211, 211, 211, 255))
        gradient5.setColorAt(1, QColor(211, 211, 211, 255))
        brush7 = QBrush(gradient5)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        gradient6 = QLinearGradient(0, 0, 1, 0)
        gradient6.setSpread(QGradient.PadSpread)
        gradient6.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient6.setColorAt(0, QColor(211, 211, 211, 255))
        gradient6.setColorAt(0.0454545, QColor(211, 211, 211, 255))
        gradient6.setColorAt(1, QColor(211, 211, 211, 255))
        brush8 = QBrush(gradient6)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush8)
        gradient7 = QLinearGradient(0, 0, 1, 0)
        gradient7.setSpread(QGradient.PadSpread)
        gradient7.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient7.setColorAt(0, QColor(211, 211, 211, 255))
        gradient7.setColorAt(0.0454545, QColor(211, 211, 211, 255))
        gradient7.setColorAt(1, QColor(211, 211, 211, 255))
        brush9 = QBrush(gradient7)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush9)
        gradient8 = QLinearGradient(0, 0, 1, 0)
        gradient8.setSpread(QGradient.PadSpread)
        gradient8.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient8.setColorAt(0, QColor(211, 211, 211, 255))
        gradient8.setColorAt(0.0454545, QColor(211, 211, 211, 255))
        gradient8.setColorAt(1, QColor(211, 211, 211, 255))
        brush10 = QBrush(gradient8)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush10)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet(u"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(211, 211, 211, 255), stop:0.0454545 rgba(211, 211, 211, 255), stop:1 rgba(211, 211, 211, 255));")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.icon_only_widget = QWidget(self.centralwidget)
        self.icon_only_widget.setObjectName(u"icon_only_widget")
        self.icon_only_widget.setGeometry(QRect(0, 0, 121, 661))
        self.icon_only_widget.setStyleSheet(u"background-color: rgb(62, 62, 62);")
        self.pushButton_6 = QPushButton(self.icon_only_widget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(40, 250, 31, 31))
        icon = QIcon()
        icon.addFile(u"H:/JEGA y MEDIA TECNICA/Proyectos finales/SmartAsis/App_SmartAsis/Imagenes app/studentssmall2.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QSize(20, 20))
        self.pushButton_7 = QPushButton(self.icon_only_widget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(40, 310, 31, 31))
        icon1 = QIcon()
        icon1.addFile(u"H:/JEGA y MEDIA TECNICA/Proyectos finales/SmartAsis/App_SmartAsis/Imagenes app/teacherssmall2.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QSize(20, 20))
        self.pushButton_8 = QPushButton(self.icon_only_widget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(40, 380, 31, 31))
        icon2 = QIcon()
        icon2.addFile(u"H:/JEGA y MEDIA TECNICA/Proyectos finales/SmartAsis/App_SmartAsis/Imagenes app/dashboardsmall2.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_8.setIcon(icon2)
        self.pushButton_8.setIconSize(QSize(20, 20))
        self.pushButton_9 = QPushButton(self.icon_only_widget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(30, 580, 61, 61))
        icon3 = QIcon()
        icon3.addFile(u":/Principal/signoutsmall1.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_9.setIcon(icon3)
        self.pushButton_9.setIconSize(QSize(30, 30))
        self.pushButton_10 = QPushButton(self.icon_only_widget)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(60, 450, 31, 31))
        icon4 = QIcon()
        icon4.addFile(u"H:/JEGA y MEDIA TECNICA/Proyectos finales/SmartAsis/App_SmartAsis/Imagenes app/settingssmall2.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setIconSize(QSize(20, 20))
        self.label_3 = QLabel(self.icon_only_widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 0, 101, 121))
        self.label_3.setMinimumSize(QSize(40, 40))
        self.label_3.setPixmap(QPixmap(u":/Principal/Logo app.png"))
        self.label_3.setScaledContents(True)
        self.Icon_text_widget = QWidget(self.centralwidget)
        self.Icon_text_widget.setObjectName(u"Icon_text_widget")
        self.Icon_text_widget.setGeometry(QRect(130, 0, 171, 661))
        self.Icon_text_widget.setStyleSheet(u"background-color: rgb(133, 133, 133);")
        self.pushButton_11 = QPushButton(self.Icon_text_widget)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(10, 120, 101, 31))
        self.pushButton_11.setStyleSheet(u"border-radius:15px;\n"
"font: 10pt \"Holy Friday\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        icon5 = QIcon()
        icon5.addFile(u"H:/JEGA y MEDIA TECNICA/Proyectos finales/SmartAsis/App_SmartAsis/Imagenes app/institutionsmall2.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_11.setIcon(icon5)
        self.pushButton_11.setIconSize(QSize(20, 20))
        self.pushButton_12 = QPushButton(self.Icon_text_widget)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(10, 170, 91, 31))
        self.pushButton_12.setStyleSheet(u"border-radius:15px;\n"
"font: 10pt \"Holy Friday\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_12.setIcon(icon4)
        self.pushButton_12.setIconSize(QSize(20, 20))
        self.pushButton_13 = QPushButton(self.Icon_text_widget)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(10, 280, 141, 31))
        self.pushButton_13.setStyleSheet(u"border-radius:15px;\n"
"font: 10pt \"Holy Friday\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(48, 79, 79);")
        icon6 = QIcon()
        icon6.addFile(u"H:/JEGA y MEDIA TECNICA/Proyectos finales/SmartAsis/App_SmartAsis/Imagenes app/add student.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_13.setIcon(icon6)
        self.pushButton_13.setIconSize(QSize(20, 20))
        self.pushButton_15 = QPushButton(self.Icon_text_widget)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(10, 350, 141, 31))
        self.pushButton_15.setStyleSheet(u"border-radius:15px;\n"
"font: 10pt \"Holy Friday\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(48, 79, 79);")
        self.pushButton_15.setIcon(icon6)
        self.pushButton_15.setIconSize(QSize(20, 20))
        self.pushButton_14 = QPushButton(self.Icon_text_widget)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(20, 600, 131, 31))
        self.pushButton_14.setStyleSheet(u"border-radius:15px;\n"
"font: 10pt \"Holy Friday\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(48, 79, 79);")
        icon7 = QIcon()
        icon7.addFile(u"H:/JEGA y MEDIA TECNICA/Proyectos finales/SmartAsis/App_SmartAsis/Imagenes app/signoutsmall2.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_14.setIcon(icon7)
        self.pushButton_14.setIconSize(QSize(20, 20))
        self.label_2 = QLabel(self.Icon_text_widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 20, 81, 81))
        self.label_2.setMinimumSize(QSize(40, 40))
        self.label_2.setPixmap(QPixmap(u":/Principal/logo_colegio.jpg"))
        self.label_2.setScaledContents(True)
        self.main_screen_widget = QWidget(self.centralwidget)
        self.main_screen_widget.setObjectName(u"main_screen_widget")
        self.main_screen_widget.setGeometry(QRect(300, 180, 601, 481))
        self.main_screen_widget.setStyleSheet(u"color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.147727 rgba(104, 129, 50, 255), stop:1 rgba(45, 94, 52, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0.0113636, y1:1, x2:1, y2:0, stop:0.363636 rgba(101, 127, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton_16 = QPushButton(self.main_screen_widget)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(40, 320, 231, 41))
        self.pushButton_16.setStyleSheet(u"border: 4px solid black;\n"
"border-radius: 20px;\n"
"background-color: rgb(224, 196, 24);\n"
"font: 14pt \"Holy Friday\";\n"
"color:black;\n"
"")
        icon8 = QIcon()
        icon8.addFile(u":/Principal/add student.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_16.setIcon(icon8)
        self.pushButton_16.setIconSize(QSize(25, 25))
        self.pushButton_17 = QPushButton(self.main_screen_widget)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(310, 320, 211, 41))
        self.pushButton_17.setStyleSheet(u"border: 4px solid black;\n"
"border-radius: 20px;\n"
"background-color: rgb(224, 196, 24);\n"
"font: 14pt \"Holy Friday\";\n"
"color:black;\n"
"\n"
"")
        self.label_4 = QLabel(self.main_screen_widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(60, 110, 191, 191))
        self.label_4.setMinimumSize(QSize(40, 40))
        self.label_4.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(21, 101, 51);\n"
"font: 14pt \"Holy Friday\";\n"
"color: white;\n"
"")
        self.label_4.setPixmap(QPixmap(u":/Principal/gestion 2.png"))
        self.label_4.setScaledContents(True)
        self.label_5 = QLabel(self.main_screen_widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(320, 110, 191, 191))
        self.label_5.setMinimumSize(QSize(40, 40))
        self.label_5.setStyleSheet(u"border-radius:95px;\n"
"background-color: rgb(21, 101, 51);\n"
"font: 14pt \"Holy Friday\";\n"
"color: white;\n"
"")
        self.label_5.setPixmap(QPixmap(u":/Principal/asistencia_logo.png"))
        self.label_5.setScaledContents(True)
        self.pushButton_20 = QPushButton(self.main_screen_widget)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setGeometry(QRect(70, 30, 211, 41))
        self.pushButton_20.setStyleSheet(u"border: 4px solid black;\n"
"border-radius: 20px;\n"
"background-color: rgb(211, 211, 211);\n"
"font: 14pt \"Holy Friday\";\n"
"color:black;\n"
"\n"
"")
        self.comboBox = QComboBox(self.main_screen_widget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(320, 380, 181, 41))
        self.comboBox.setStyleSheet(u"border: 4px solid black;\n"
"border-radius: 10px;\n"
"background-color: rgb(224, 196, 24);\n"
"font: 14pt \"Holy Friday\";\n"
"color:black;\n"
"")
        self.label_6 = QLabel(self.main_screen_widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(310, 50, 131, 31))
        self.header_widget = QWidget(self.centralwidget)
        self.header_widget.setObjectName(u"header_widget")
        self.header_widget.setGeometry(QRect(300, 0, 611, 181))
        self.header_widget.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label = QLabel(self.header_widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 50, 261, 81))
        self.label.setStyleSheet(u"font: 24pt \"Holy Friday\";\n"
"color: rgb(0, 0, 0);")
        self.lineEdit = QLineEdit(self.header_widget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(340, 80, 181, 31))
        self.lineEdit.setStyleSheet(u"border-radius:15px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Holy Friday\";\n"
"color: rgb(195, 195, 195);")
        self.pushButton_18 = QPushButton(self.header_widget)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(530, 70, 41, 41))
        icon9 = QIcon()
        icon9.addFile(u"H:/JEGA y MEDIA TECNICA/Proyectos finales/SmartAsis/App_SmartAsis/Imagenes app/profile.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_18.setIcon(icon9)
        self.pushButton_18.setIconSize(QSize(40, 40))
        self.pushButton_19 = QPushButton(self.header_widget)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(10, 70, 41, 41))
        self.pushButton_19.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        icon10 = QIcon()
        icon10.addFile(u"H:/JEGA y MEDIA TECNICA/Proyectos finales/SmartAsis/App_SmartAsis/Imagenes app/menu (1).png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_19.setIcon(icon10)
        self.pushButton_19.setIconSize(QSize(40, 40))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 900, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton_6.setText("")
        self.pushButton_7.setText("")
        self.pushButton_8.setText("")
        self.pushButton_9.setText("")
        self.pushButton_10.setText("")
        self.label_3.setText("")
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"Instituci\u00f3n", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"Perfil", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"Gesti\u00f3n de estudiantes", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"Gesti\u00f3n de Asistencia", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"Salir de la app", None))
        self.label_2.setText("")
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"Gesti\u00f3n de estudiantes", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"Asistencia", None))
        self.label_4.setText("")
        self.label_5.setText("")
        self.pushButton_20.setText(QCoreApplication.translate("MainWindow", u"Comencemos...", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Registrar", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Ver asistencias", None))

        self.label_6.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u00a1Bienvenido Usuario!", None))
        self.lineEdit.setText(QCoreApplication.translate("MainWindow", u"Busca Aqu\u00ed...", None))
        self.pushButton_18.setText("")
        self.pushButton_19.setText("")
    # retranslateUi

